services:
  llamacpp-server:
    image: ghcr.io/ggerganov/llama.cpp:server
    ports:
      - 8080:8080
    volumes:
      - ./models:/models
    command: --lora /models/Vikhr-Llama-3.2-1B-Instruct-Summary-Adapter-q8_0.gguf --lora /models/Vikhr-Llama-3.2-1B-Instruct-Generate-Adapter-q8_0.gguf
    environment:
      LLAMA_ARG_MODEL: /models/Vikhr-Llama-3.2-1B-Q8_0.gguf
      LLAMA_ARG_CTX_SIZE: 2048
      LLAMA_ARG_PORT: 8080

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "0.0.0.0:8000:8000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/
      - MONGO_DATABASE=database
      - MONGO_COLLECTION=documents

      - SUMMARY_LORA_ADAPTER_ID=0
      - GENERATE_LORA_ADAPTER_ID=1
    depends_on:
      - mongodb
      - tika

  mongodb:
    image: mongo
    ports:
      - "8001:27017"
    volumes:
      - mongodb_data:/data/db

  tika:
    image: apache/tika

volumes:
  mongodb_data: